name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Change this if you're using a different branch
  pull_request:
    branches:
      - main  # Change this if you're using a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # You can change this version as per your requirement

      - name: Install dependencies
        run: npm install

      - name: Build and Deploy to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "/"  # Root directory of your app
          output_location: "/"  # Build directory (for static sites, it's root)
